version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/static
      - media_volume:/usr/src/media
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    command: gunicorn Portfolioblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/static
      - static_volume:/usr/src/media
      - ./:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume: